[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
TRADING_BUDGET = "100.0"
MAX_RISK_PER_TRADE = "0.03"
DAILY_LOSS_LIMIT = "0.15"
MIN_TRADE_AMOUNT = "5.0"
LOG_LEVEL = "INFO"
